# permissions for end users to edit cinderellas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cinderella-editor-role
rules:
- apiGroups:
  - cinderella.sho2010.dev
  resources:
  - cinderellas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cinderella.sho2010.dev
  resources:
  - cinderellas/status
  verbs:
  - get
