# permissions for end users to view cinderellas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cinderella-viewer-role
rules:
- apiGroups:
  - cinderella.sho2010.dev
  resources:
  - cinderellas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cinderella.sho2010.dev
  resources:
  - cinderellas/status
  verbs:
  - get
