apiVersion: cinderella.sho2010.dev/v1alpha1
kind: Cinderella
metadata:
  name: cinderella-sample
spec:
  term:
    expiresAfter: "60m"
  encryption:
    github:
      user: sho2010
      key: 1 # Optional
